# Markdown 검사에서 제외할 디렉토리와 파일입니다.
exclude_dirs = [
  "00_readme.md",
  "99_archive",
  "99_etc",
  "__pycache__",
  ".git",
  "_reference",
]
exclude_files = [
  "CHANGELOG.md",
  "LICENSE.md",
  "TODO.md",
  "license_guide.md",
]
